#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <ctime>
#include <iomanip>
#include <chrono>
#include <poll.h>
#include <unistd.h>

// colors
#define RESET   "\033[0m"
#define RED     "\033[1;31m"
#define GOLD    "\033[38;2;255;215;0m"   
#define GREEN   "\033[38;2;0;255;0m"     
#define CYAN    "\033[38;2;0;255;255m"   

double timeToSeconds(std::string s) {
    std::vector<double> parts;
    std::stringstream ss(s);
    std::string item;
    while (std::getline(ss, item, ':')) {
        try { parts.push_back(std::stod(item)); }  
        catch (...) { return -1; } 
    }
    if (parts.size() == 3) return (parts[0] * 3600) + (parts[1] * 60) + parts[2];
    if (parts.size() == 2) return (parts[0] * 60) + parts[1];
    if (parts.size() == 1) return parts[0];
    return -1;
}
// html part
void generateHTML(const std::vector<std::string>& kingdoms, const std::vector<double>& times, double total) {
    std::time_t now = std::time(0);
    std::tm* ltm = std::localtime(&now);
    std::stringstream ss;
    ss << "summary_" << 1900 + ltm->tm_year << "-" << std::setfill('0') << std::setw(2) << 1 + ltm->tm_mon << "-" 
       << std::setfill('0') << std::setw(2) << ltm->tm_mday << "_" << std::setfill('0') << std::setw(2) << ltm->tm_hour 
       << std::setfill('0') << std::setw(2) << ltm->tm_min << ".html";
    
    std::string filename = ss.str();
    const char* homeDir = std::getenv("HOME");
    std::string path = (homeDir != nullptr) ? std::string(homeDir) + "/Documents/" + filename : filename;

    std::ofstream html(path);
    if (!html.is_open()) return;

    char* dt = std::ctime(&now);
    int h = (int)total / 3600, m = ((int)total % 3600) / 60;
    double s = total - (h * 3600) - (m * 60);

    html << "<!DOCTYPE html><html><head><title>summary</title><style>";
    html << "body{background:#121212;color:#e0e0e0;font-family:monospace;padding:40px;}";
    html << ".container{max-width:600px;margin:auto;border:1px solid #333;padding:20px;border-radius:8px;}";
    html << "h1{color:#e60012;border-bottom:2px solid #e60012;padding-bottom:5px;margin:0;}";
    html << ".timestamp{font-size:12px;color:#888;margin-bottom:20px;margin-top:5px;}";
    html << ".total{font-size:24px;color:#00ff00;margin:20px 0;}";
    html << "table{width:100%;border-collapse:collapse;} td{padding:8px;border-bottom:1px solid #222;}";
    html << ".footer{margin-top:30px;font-size:10px;color:#555;text-align:center;}</style></head><body>";
    html << "<div class='container'><h1>mission summary</h1><div class='timestamp'>" << dt << "</div>";
    html << "<div class='total'>final time: " << h << "h " << m << "m " << std::fixed << std::setprecision(2) << s << "s</div>";
    html << "<table>";
    for(size_t i=0; i<kingdoms.size(); ++i) html << "<tr><td>" << kingdoms[i] << "</td><td style='text-align:right;'>" << times[i] << "s</td></tr>";
    html << "</table><div class='footer'>generated by smosummary | tool by aray4iv3</div></div></body></html>";
    html.close();
    std::cout << "\n[" << GREEN << "success" << RESET << "] saved: " << filename << std::endl;
}
// --version -v flags
int main(int argc, char* argv[]) {
    bool stopwatchMode = false;
    if (argc > 1) {
        std::string flag = argv[1];
        if (flag == "--version" || flag == "-v") {
            std::cout << GOLD << "smosummary v2.2.0-1\ncreator: aray4iv3" << RESET << std::endl;
            return 0; 
        }
        if (flag == "--stopwatch" || flag == "-s") stopwatchMode = true; // stopwatch flag -s --stopwatch
    }

    std::vector<std::string> lake = {"cap", "cascade", "sand", "lake", "cloud", "lost", "metro", "snow", "seaside", "luncheon", "ruined", "bowser's", "moon"};
    std::vector<std::string> wooded = {"cap", "cascade", "sand", "wooded", "cloud", "lost", "metro", "snow", "seaside", "luncheon", "ruined", "bowser's", "moon"};
    std::vector<std::string> hunder = {"mushroom", "cap", "cascade", "sand", "lake", "wooded", "cloud", "lost", "metro", "snow", "seaside", "luncheon", "ruined", "bowser's", "moon", "dark side", "darker side"};
    std::vector<double> times; std::vector<std::string> active; std::string in; int route = 0, mode = 1;

    std::cout << GOLD << "--- smosummary: " << (stopwatchMode ? "stopwatch" : "manual") << " ---" << RESET << std::endl;
    // route mode for stopwatch
    while (true) {
        std::cout << "\nselect route:\n1) any% (lake)\n2) any% (wooded)\n3) 100%\n4) custom\n5) import .txt\nselection > ";
        if (!(std::cin >> route)) { std::cin.clear(); std::cin.ignore(1000, '\n'); continue; }
        if (route == 1) { active = lake; break; }
        if (route == 2) { active = wooded; break; }
        if (route == 3) { active = hunder; break; }
        if (route == 4) {
            int c; std::cout << "how many segments? "; std::cin >> c;
            for(int i=0; i<c; ++i) { std::string n; std::cout << "name " << i+1 << ": "; std::cin >> n; active.push_back(n); }
            break;
        }
        if (route == 5) {
            std::string f; std::cout << "path: "; std::cin >> f; std::ifstream iF(f);
            if (iF.is_open()) { std::string l; while(std::getline(iF, l)) if(!l.empty()) active.push_back(l); iF.close(); break; }
        }
    }
	// modes for stopwatch
    std::cout << "\nchoose mode:\n1) split\n2) cumulative\nselection > "; std::cin >> mode;

    if (stopwatchMode) {
        std::cout << GREEN << "\nstopwatch ready." << RESET << " hit enter." << std::endl;
        std::cin.ignore(1000, '\n'); std::cin.get();
        auto start = std::chrono::high_resolution_clock::now(); auto last = start;
        struct pollfd pfd = {STDIN_FILENO, POLLIN, 0};
        for (const std::string& k : active) {
            while (true) {
                auto now = std::chrono::high_resolution_clock::now();
                std::chrono::duration<double> d = now - last;
                std::cout << "\r\033[K" << CYAN << std::left << std::setw(12) << k << RESET << " | " << std::fixed << std::setprecision(2) << d.count() << "s" << std::flush;
                if (poll(&pfd, 1, 33) > 0) { std::cin.get(); times.push_back(d.count()); std::cout << "\n" << GREEN << " >> saved" << RESET << std::endl; last = now; break; }
            }
        }
    } else {
        for (const std::string& k : active) {
            while (true) { std::cout << CYAN << k << RESET << " > "; std::cin >> in; double s = timeToSeconds(in); if (s >= 0) { times.push_back(s); break; } }
        }
    }

    double total = 0; for (double t : times) total += t;
    std::cout << "\ngenerate html? (y/n): "; char ex; std::cin >> ex;
    if (ex == 'y' || ex == 'Y') generateHTML(active, times, total);
    return 0;
}

